services:
  api:
    container_name: pdf-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - ./tmp:/tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    name: toolbox-net
